services:
  web:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - skku-table-nginx:/etc/nginx
    depends_on:
      - application
  application:
    container_name: spring
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: skku-table
    volumes:
      - skku-table-database:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  skku-table-nginx:
  skku-table-database: