services:
  reverse-proxy:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - skku-table-nginx:/etc/nginx
  database:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: skku-table
    volumes:
      - skku-table-database:/var/lib/mysql
    ports:
      - 3306:3306

  spring-boot-app:
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile # Dockerfile을 참조합니다.
      args:
        JAR_FILE: build/libs/skku-table-backend.jar
    ports:
      - 8080:8080 # Spring Boot 애플리케이션을 8080 포트로 매핑
    depends_on:
      - database # 데이터베이스가 먼저 시작되도록 의존성 설정
    environment:
      SPRING_PROFILES_ACTIVE: dev # 필요한 프로파일 설정 (예: 개발 환경)
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/skku-table


volumes:
  skku-table-nginx:
  skku-table-database: