services:
  reverse-proxy:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - skku-table-nginx:/etc/nginx
  database:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: skku-table
    volumes:
      - skku-table-database:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  skku-table-nginx:
  skku-table-database: